spring:
  datasource:
    url: jdbc:mysql://${db.host:localhost}:3306/${db.scheme:demo}
    username: ${db.username:root}
    password: ${db.password:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.port:6379}

jwt:
  secret: ${kt.jwt.secret:1234567890123456789012345678901234}
  access-token-expiration: ${kt.jwt.access-token-expiration:300000}
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000}


slack:
  bot-token: ${slack.token:1234}
  log-channel: ${slack.channel:1234}